<?php

return [
    'destination_root' => storage_path('app/private/ipil-rescue/snapshots'),
    'chunk_size' => 500,
    'media_attempts' => 3,
    'required_datasets' => [
        'activity_logs',
        'assetSizes',
        'authAccounts',
        'authRateLimits',
        'authRefreshTokens',
        'authSessions',
        'authVerificationCodes',
        'authVerifiers',
        'barangays',
        'billing_group_fee_fields',
        'billing_group_fees',
        'billing_group_fields',
        'billing_group_line_items',
        'billing_group_print_layouts',
        'billing_group_records',
        'billing_groups',
        'business_categories',
        'business_nature_categories',
        'business_owners',
        'business_permit_applications',
        'business_subcategories',
        'businesses',
        'cities',
        'clearance_types',
        'counters',
        'departments',
        'division_groups',
        'divisions',
        'fee_names',
        'fee_overrides',
        'fees',
        'groups',
        'majors',
        'manual_transactions',
        'mayorsPermitCategories',
        'payment_schedule_config',
        'payment_schedules',
        'payments',
        'permissions',
        'permit_clearances',
        'permit_layouts',
        'permits',
        'platform_settings',
        'provinces',
        'receipt_layouts',
        'report_export_chunks',
        'report_exports',
        'role_permissions',
        'roles',
        'saved_reports',
        'surcharge_penalty_config',
        'unitsOfMeasurement',
        'users',
    ],

    'source' => [
        'driver' => 'convex-export',
        'deployment' => env('IPIL_RESCUE_CONVEX_DEPLOYMENT'),
        'convex_url' => env('IPIL_RESCUE_CONVEX_URL'),
        'deploy_key' => env('IPIL_RESCUE_CONVEX_DEPLOY_KEY'),
        'user_token' => env('IPIL_RESCUE_CONVEX_USER_TOKEN'),
        'read_only_approved' => env('IPIL_RESCUE_SOURCE_READ_ONLY', false),
        'convex_cli' => env('IPIL_RESCUE_CONVEX_CLI'),
        'project_path' => env('IPIL_RESCUE_LEGACY_PROJECT_PATH'),
        'schema_path' => env('IPIL_RESCUE_LEGACY_SCHEMA_PATH'),
    ],

    'pricing' => [
        'manifest_path' => env('IPIL_RESCUE_PRICING_MANIFEST'),
    ],
];
