<?php

return [
    'mode' => (bool) env('STAKEHOLDER_PREVIEW_MODE', false),
    'profile' => env('STAKEHOLDER_PREVIEW_PROFILE'),
    'data_classification' => env('STAKEHOLDER_PREVIEW_DATA_CLASSIFICATION'),
    'pii_mode' => env('STAKEHOLDER_PREVIEW_PII_MODE'),
    'production_migration_enabled' => (bool) env('STAKEHOLDER_PREVIEW_PRODUCTION_MIGRATION_ENABLED', true),
    'production_integrations' => env('STAKEHOLDER_PREVIEW_PRODUCTION_INTEGRATIONS'),
    'password' => env('STAKEHOLDER_PREVIEW_PASSWORD'),
    'accounts' => [
        'citizen' => env('STAKEHOLDER_PREVIEW_CITIZEN_EMAIL', 'stakeholder.preview.citizen@example.test'),
        'bplo' => env('STAKEHOLDER_PREVIEW_BPLO_EMAIL', 'stakeholder.preview.bplo@example.test'),
        'assessment_officer' => env('STAKEHOLDER_PREVIEW_ASSESSMENT_OFFICER_EMAIL', 'stakeholder.preview.assessment-officer@example.test'),
        'treasury' => env('STAKEHOLDER_PREVIEW_TREASURY_EMAIL', 'stakeholder.preview.treasury@example.test'),
        'municipal_treasurer' => env('STAKEHOLDER_PREVIEW_MUNICIPAL_TREASURER_EMAIL', 'stakeholder.preview.municipal-treasurer@example.test'),
        'cashier' => env('STAKEHOLDER_PREVIEW_CASHIER_EMAIL', 'stakeholder.preview.cashier@example.test'),
        'management' => env('STAKEHOLDER_PREVIEW_MANAGEMENT_EMAIL', 'stakeholder.preview.management@example.test'),
        'engineering' => env('STAKEHOLDER_PREVIEW_ENGINEERING_EMAIL', 'stakeholder.preview.engineering@example.test'),
        'mpdo' => env('STAKEHOLDER_PREVIEW_MPDO_EMAIL', 'stakeholder.preview.mpdo@example.test'),
        'assessor' => env('STAKEHOLDER_PREVIEW_ASSESSOR_EMAIL', 'stakeholder.preview.assessor@example.test'),
        'health' => env('STAKEHOLDER_PREVIEW_HEALTH_EMAIL', 'stakeholder.preview.health@example.test'),
        'menro' => env('STAKEHOLDER_PREVIEW_MENRO_EMAIL', 'stakeholder.preview.menro@example.test'),
        'mayor_office' => env('STAKEHOLDER_PREVIEW_MAYOR_OFFICE_EMAIL', 'stakeholder.preview.mayor-office@example.test'),
        'releasing' => env('STAKEHOLDER_PREVIEW_RELEASING_EMAIL', 'stakeholder.preview.releasing@example.test'),
    ],
    'weekend_hypothesis' => [
        'semantic_classification' => 'provisional_uat',
        'application_type' => 'new',
        'payment_scenario' => 'full_consolidated',
        'office_charges' => [
            'engineering' => ['label' => 'Municipal Engineering Office', 'scenario_amount_cents' => 125_00],
            'mpdo' => ['label' => 'MPDO / MPDC', 'scenario_amount_cents' => 80_00],
            'assessor' => ['label' => "Municipal Assessor's Office", 'scenario_amount_cents' => 60_00],
            'health' => ['label' => 'Municipal Health Office', 'scenario_amount_cents' => 95_00],
            'menro' => ['label' => 'MENRO', 'scenario_amount_cents' => 40_00],
        ],
        'permit_number_prefix' => 'UAT-IPIL',
        'synthetic_signature_reference' => 'SYNTHETIC-UAT-MAYOR-SIGNATURE',
    ],
];
